### ISSUE TITLE
Avaliação da primeira etapa

### ISSUE THREAD

**Issue by santos-fernando** [JefiPNZ/ChatIO-projeto#1]
EQUIPE		NOTA: 1.25 (nota máxima da etapa: 1.5)
	Bruno
	Jeferson
	
ALOCAÇÃO DAS TAREFAS
Ok.

DIAGRAMA DE SEQUÊNCIA DEFINITIVO PROTOCOLO CLIENTE/SERVIDOR
Não estão especificados quais são os dados enviados para o servidor em cada mensagem. 
Não foi especificado mensagem para atender o RF2.

DIAGRAMA DE CLASSE SERVIDOR
Ok.

DIAGRAMA DE SEQUÊNCIA PRELIMINAR CLIENTE/CLIENTE
O procolo pode ser simplificado, pois não há a necessidade de "MESSAGE_CONNECT". Isto pode ser absorvido pela mensagem de envio de texto e de arquivo.
Qual a finalidade da mensagem "MESSAGE_CONNECT" entre o Cliente2 e o Cliente1?  Qual a diferença para a "MESSAGE_CONNECT" anterior? Idem para a "MESSAGE_TEXT".
Não estão especificados quais são os dados enviados para o cliente em cada mensagem TEXT e FILE. 
Sugestão: não há a necessidade de ter um retorno de "MESSAGE***RECEIVED", pois ao usar o protocolo TCP, a entrega/recebimento é garantido.

OBSERVAÇÕES
Os acadêmicos podem realizar os ajustes solicitados e fazer push até 11/11 ao meio-dia para melhorar a nota desta etapa.

**Comment by JefiPNZ** [comment]
Ajustado.
